FROM postgres:14-alpine

EXPOSE 5432

# Add a custom initialization script
COPY ./schema.sql /docker-entrypoint-initdb.d/

# Use the default command to run PostgreSQL
ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["postgres"]